### ISSUE TITLE
MX250 2GB GDDR5

### ISSUE THREAD

**Issue by takobaba** [MokkaSchnalle/macOS-Dell-5411-5511#2]
Does yours have an Nvidia MX250 as well, I found Dell 5411 laptop. I am thinking of buying but ending up disabling the gpu seems like a bit of a waste. What do you think?

**Comment by MokkaSchnalle** [comment]
mine is UHD 630 only. The Nvidia would be unavailable in macOS but fully working in Windows if needed.
Just use `-wegnoegpu` for WhateverGreen.

AFAIK there is no 4K display option for these machines, so do you need GPU performance outside of macOS?
If not, just save the bucks and get a iGPU only model.

**Comment by takobaba** [comment]
I ended up grabbing a thinkpad L490 with only iGPU.

Thanks for your comment!
