### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by jaysunneu** [MokkaSchnalle/macOS-Dell-5411-5511#3]
What configuration has been made for HDMI? My device is latitude 5501 and the CPU is 9850H. The external HDMI cannot be used normally. ask for help

**Comment by MokkaSchnalle** [comment]
Well, this is a completely different device. The connector mapping is unique for every device.
Do you have a dGPU in your model?

You can try to use the Whatevergreen config without support for multiple displays via Thunderbolt. Checkout older commits.
If this is not working, then you have to do try and error with your Whatevergreen config. See lspcon connector which is the HDMI port:

<key>framebuffer-con3-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-con3-alldata</key>
<data>AwQSAAAEAACHAQAA</data>
<key>enable-lspcon-support</key>
<data>AQAAAA==</data>
<key>framebuffer-con3-has-lspcon</key>
<data>AQAAAA==</data>

Also read the OpenCore iGPU mapping guide:
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html
https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/busid.html#parsing-the-framebuffer

In addition, take a look at the block diagram of your laptop's logic board to understand how the display ports are connected to the CPU.
